"""
Build report-ready tables and summaries from training outputs.

Run after training (and after visualize_predictions.py + rpn_proposal_analysis.py if you use them).

Writes under --output_dir (default: outputs/report):
  - report_tables.md           Markdown tables (paste into Google Docs / convert to PDF)
  - report_narrative_draft.md  Editable intro / method / results / analysis / conclusion (you refine)
  - report_tables.tex          LaTeX tabular snippets
  - metrics_summary.csv        Flat CSV for Excel
  - rpn_recall_table.csv       If rpn_recall.json exists
  - REPORT_CHECKLIST.txt       Assignment-oriented checklist + file paths
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


def load_metrics(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def best_row(history: List[Dict[str, Any]], key: str = "bbox_AP") -> Optional[Dict[str, Any]]:
    if not history:
        return None
    return max(history, key=lambda r: float(r.get(key, -1.0)))


def fmt(x: Any, nd: int = 4) -> str:
    if x is None:
        return ""
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def bbox_keys(prefix: str = "bbox_") -> List[str]:
    return [f"{prefix}AP", f"{prefix}AP50", f"{prefix}AP75", f"{prefix}APs", f"{prefix}APm", f"{prefix}APl"]


def segm_keys() -> List[str]:
    return ["segm_AP", "segm_AP50", "segm_AP75", "segm_APs", "segm_APm", "segm_APl"]


def write_md(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_narrative_draft(
    best_f: Optional[Dict[str, Any]],
    best_m: Optional[Dict[str, Any]],
    last_f: Optional[Dict[str, Any]],
    last_m: Optional[Dict[str, Any]],
    hist_f: List[Dict[str, Any]],
    hist_m: List[Dict[str, Any]],
    rpn_exists: bool,
    out_dir: Path,
) -> str:
    """Long-form draft; student replaces [EDIT: ...] and tightens prose."""
    nf = len(hist_f)
    nm = len(hist_m)
    ap_f = fmt(best_f.get("bbox_AP")) if best_f else "[no Faster R-CNN metrics]"
    ap_m_box = fmt(best_m.get("bbox_AP")) if best_m else "[no Mask R-CNN metrics]"
    ap_m_mask = fmt(best_m.get("segm_AP")) if best_m and best_m.get("segm_AP") is not None else "[n/a]"

    lines: List[str] = []
    lines.append("# Report narrative draft (EDIT FREELY)\n\n")
    lines.append(
        "> **Generated by `export_report_tables.py`.** This is a **starting outline**: replace every "
        "`[EDIT: ...]` with your own details, shorten or expand sections, and fix wording for your course. "
        "Numbers below are **auto-filled** from `metrics.json` where available.\n\n"
    )

    lines.append("## Abstract\n\n")
    lines.append(
        f"This work studies object detection and instance segmentation on a **3,000 / 500 image** subset of "
        f"COCO 2017 using **Faster R-CNN** (ResNet-50-FPN) and **Mask R-CNN** (ResNet-50-FPN) in PyTorch/torchvision, "
        f"fine-tuned from COCO-pretrained weights. "
        f"At the best validation epoch by box AP, Faster R-CNN reached **bbox AP ≈ {ap_f}** and "
        f"Mask R-CNN reached **bbox AP ≈ {ap_m_box}** and **mask AP ≈ {ap_m_mask}**. "
        f"[EDIT: Add one sentence on main finding or limitation.]\n\n"
    )

    lines.append("## 1. Introduction and motivation\n\n")
    lines.append(
        "Object detection and instance segmentation are core vision tasks with applications in "
        "robotics, autonomous systems, and scene understanding. The COCO dataset is challenging due to "
        "scale variation, occlusion, and clutter. This case study implements **Faster R-CNN** for detection "
        "and **Mask R-CNN** for pixel-accurate instance masks, and analyzes **RPN proposals**, **FPN**, "
        "and **RoI Align** versus **RoI Pooling** in the report text. "
        "[EDIT: Add your motivation and any course-specific framing.]\n\n"
    )

    lines.append("## 2. Methodology\n\n")
    lines.append("### 2.1 Faster R-CNN\n\n")
    lines.append(
        "- **Backbone:** ResNet-50 extracts feature maps; **FPN** builds a multi-scale feature pyramid.\n"
        "- **RPN:** Sliding-window style anchors on each level propose candidate regions; outputs objectness "
        "and box regression relative to anchors.\n"
        "- **RoI head:** RoI features are pooled (RoI Pool / aligned features in the full Mask R-CNN line); "
        "parallel branches predict **class logits** and **box refinements**.\n"
        "- **Losses:** Multi-task sum of RPN classification + regression and detection classification + "
        "Smooth L1 box regression. [EDIT: Add formula or citation if your rubric requires it.]\n\n"
    )
    lines.append("### 2.2 Mask R-CNN\n\n")
    lines.append(
        "- Extends Faster R-CNN with a **mask branch**: for each positive RoI, a small FCN predicts a "
        "**K×M binary mask** (class-specific in design).\n"
        "- **RoI Align** uses bilinear sampling without quantizing RoI boundaries, reducing misalignment "
        "especially at object boundaries versus RoI Pooling.\n"
        "- **Total loss:** \\(L = L_{\\text{cls}} + L_{\\text{box}} + L_{\\text{mask}}\\) "
        "(mask term is typically per-pixel sigmoid BCE). [EDIT: Expand if required.]\n\n"
    )

    lines.append("## 3. Experimental setup\n\n")
    lines.append(
        "- **Data:** COCO 2017 **subset** — 3,000 training and 500 validation images with filtered JSON "
        "(see `build_coco_subset.py`, seed 42 unless changed).\n"
        "- **Training:** torchvision `fasterrcnn_resnet50_fpn` / `maskrcnn_resnet50_fpn` with **DEFAULT** "
        "(COCO) weights; fine-tuning with **SGD** (momentum 0.9, weight decay 5e-4), **StepLR** (step 3, γ=0.1). "
        f"**Epochs run:** Faster R-CNN = **{nf}**, Mask R-CNN = **{nm}** (from saved `metrics.json`). "
        "[EDIT: State batch size, learning rate, and partition — copy from `run_*.slurm`.]\n"
        "- **Environment:** [EDIT: e.g. UTRGV Cradle, `conda` env `maskrcnn`, Python 3.10, PyTorch cu121 wheels, "
        "`module load cuda/...`.]\n"
        "- **Hardware:** [EDIT: GPU model, e.g. NVIDIA L40S, and approximate job time from Slurm logs.]\n\n"
    )

    lines.append("## 4. Results\n\n")
    lines.append(
        "Quantitative metrics follow the **COCO** protocol (AP@[0.50:0.95], AP50, AP75, AP by scale). "
        f"**Tables** are in **`{(out_dir / 'report_tables.md').as_posix()}`** and **`metrics_summary.csv`**.\n\n"
    )
    lines.append("### 4.1 Detection (bounding boxes)\n\n")
    lines.append(
        f"- **Faster R-CNN** (best bbox epoch): AP = **{ap_f}**; see table file for AP50/AP75/APs/APm/APl.\n"
        f"- **Mask R-CNN** (same selection by bbox AP): AP = **{ap_m_box}**.\n"
        "[EDIT: Interpret: e.g. small vs large objects, comparison between models.]\n\n"
    )
    lines.append("### 4.2 Instance segmentation (Mask R-CNN)\n\n")
    lines.append(
        f"- **Mask AP** (best bbox epoch row): **{ap_m_mask}**.\n"
        "[EDIT: Compare to box AP; comment on boundary quality using figure captions.]\n\n"
    )
    lines.append("### 4.3 Qualitative examples\n\n")
    lines.append(
        f"Place figures from **`outputs/figures/frcnn/`** and **`outputs/figures/maskrcnn/`** here. "
        "[EDIT: Caption correct detections, false positives, mislocalization, missed small objects.]\n\n"
    )

    lines.append("## 5. RPN proposal analysis (Part I-D)\n\n")
    if rpn_exists:
        lines.append(
            f"Mean recall over the validation subset is summarized in **`{(out_dir / 'rpn_recall_table.csv').as_posix()}`** "
            f"and **§6 of `report_tables.md`**. "
            "[EDIT: Discuss recall vs IoU (0.5 / 0.7 / 0.9) and vs number of proposals (100 / 300 / 1000); "
            "relate proposal quality to downstream AP.]\n\n"
        )
    else:
        lines.append(
            "_[Run `rpn_proposal_analysis.py` and re-run `export_report_tables.py` to fill metrics here.]_\n\n"
        )

    lines.append("## 6. Critical analysis and tradeoffs\n\n")
    lines.append(
        "- **Compute:** Mask R-CNN adds a mask head and (typically) heavier per-image work than Faster R-CNN alone; "
        "[EDIT: compare training wall-clock or memory if you logged them].\n"
        "- **Accuracy:** [EDIT: Does the mask branch justify cost for your AP numbers?]\n"
        "- **Limitations:** Small subset vs full COCO; single seed; possible hyperparameter sensitivity (LR, NaN issues). "
        "[EDIT: Add yours.]\n\n"
    )

    lines.append("## 7. Conclusion and future work\n\n")
    lines.append(
        "We implemented and evaluated Faster R-CNN and Mask R-CNN on a manageable COCO subset. "
        f"Key numeric outcomes: **Faster R-CNN bbox AP ≈ {ap_f}**; **Mask R-CNN bbox AP ≈ {ap_m_box}**, "
        f"**mask AP ≈ {ap_m_mask}**. "
        "[EDIT: One paragraph summary + future work: e.g. longer training, stronger augmentation, other backbones.]\n\n"
    )

    lines.append("---\n\n**Submission reminders:** Slurm `.out` / `.err` logs, this repo or zip, and final PDF.\n")
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export report tables from metrics.json and RPN JSON.")
    parser.add_argument("--frcnn_metrics", type=Path, default=Path("outputs/frcnn/metrics.json"))
    parser.add_argument("--maskrcnn_metrics", type=Path, default=Path("outputs/maskrcnn/metrics.json"))
    parser.add_argument("--rpn_json", type=Path, default=Path("outputs/frcnn/rpn_recall.json"))
    parser.add_argument("--figures_frcnn", type=Path, default=Path("outputs/figures/frcnn"))
    parser.add_argument("--figures_mask", type=Path, default=Path("outputs/figures/maskrcnn"))
    parser.add_argument("--output_dir", type=Path, default=Path("outputs/report"))
    args = parser.parse_args()

    out_dir = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    hist_f = load_metrics(args.frcnn_metrics)
    hist_m = load_metrics(args.maskrcnn_metrics)

    last_f = hist_f[-1] if hist_f else None
    last_m = hist_m[-1] if hist_m else None
    best_f = best_row(hist_f, "bbox_AP")
    best_m = best_row(hist_m, "bbox_AP")

    labels = ["AP @[.50:.95]", "AP50", "AP75", "AP small", "AP medium", "AP large"]
    bkeys = bbox_keys()

    # --- Markdown ---
    lines: List[str] = []
    lines.append("# COCO subset — results for report\n")
    lines.append("Generated by `scripts/export_report_tables.py`.\n")

    lines.append("## 1) Faster R-CNN — bounding box metrics (best epoch by bbox AP)\n")
    if best_f:
        lines.append(f"- **Epoch:** {best_f.get('epoch', '')}  |  **train loss:** {fmt(best_f.get('loss'))}\n")
        lines.append("\n| Metric | Value |\n|--------|-------|\n")
        for lab, k in zip(labels, bkeys):
            lines.append(f"| {lab} | {fmt(best_f.get(k))} |\n")
    else:
        lines.append("_No data: missing `outputs/frcnn/metrics.json`._\n")

    lines.append("\n## 2) Mask R-CNN — bounding box metrics (best epoch by bbox AP)\n")
    if best_m:
        lines.append(f"- **Epoch:** {best_m.get('epoch', '')}  |  **train loss:** {fmt(best_m.get('loss'))}\n")
        lines.append("\n| Metric | Value |\n|--------|-------|\n")
        for lab, k in zip(labels, bkeys):
            lines.append(f"| {lab} | {fmt(best_m.get(k))} |\n")
    else:
        lines.append("_No data: missing `outputs/maskrcnn/metrics.json`._\n")

    lines.append("\n## 3) Mask R-CNN — mask / segmentation metrics (same epoch as §2 best bbox)\n")
    if best_m:
        sk = segm_keys()
        slabels = ["Mask AP @[.50:.95]", "Mask AP50", "Mask AP75", "Mask APs", "Mask APm", "Mask APl"]
        lines.append("\n| Metric | Value |\n|--------|-------|\n")
        for lab, k in zip(slabels, sk):
            lines.append(f"| {lab} | {fmt(best_m.get(k))} |\n")
    else:
        lines.append("_No Mask R-CNN metrics._\n")

    lines.append("\n## 4) Side-by-side comparison (best bbox epoch per model)\n")
    lines.append("\n| Metric | Faster R-CNN | Mask R-CNN (bbox) |\n|--------|--------------|-------------------|\n")
    for lab, k in zip(labels, bkeys):
        vf = fmt(best_f.get(k)) if best_f else "—"
        vm = fmt(best_m.get(k)) if best_m else "—"
        lines.append(f"| {lab} | {vf} | {vm} |\n")

    lines.append("\n## 5) Last epoch snapshot (for convergence discussion)\n")
    lines.append("\n| Model | Epoch | loss | bbox AP |\n|-------|-------|------|--------|\n")
    if last_f:
        lines.append(f"| Faster R-CNN | {last_f.get('epoch')} | {fmt(last_f.get('loss'))} | {fmt(last_f.get('bbox_AP'))} |\n")
    if last_m:
        lines.append(
            f"| Mask R-CNN | {last_m.get('epoch')} | {fmt(last_m.get('loss'))} | {fmt(last_m.get('bbox_AP'))} | "
            f"(segm AP {fmt(last_m.get('segm_AP'))})\n"
        )

    # RPN section
    if args.rpn_json.exists():
        with args.rpn_json.open(encoding="utf-8") as f:
            rpn = json.load(f)
        mr = rpn.get("mean_recall", {})
        lines.append("\n## 6) RPN proposal recall (mean over val images)\n")
        lines.append(f"- Images used: **{rpn.get('num_images', '?')}**\n")
        lines.append("\n| Setting | Mean recall |\n|---------|-------------|\n")
        for key in sorted(mr.keys()):
            lines.append(f"| `{key}` | {fmt(mr[key])} |\n")
    else:
        lines.append("\n## 6) RPN proposal recall\n")
        lines.append("_No `rpn_recall.json` — run:_\n")
        lines.append("```bash\npython scripts/rpn_proposal_analysis.py \\\n")
        lines.append("  --data_root data/coco_subset \\\n")
        lines.append("  --ann_json data/coco_subset/annotations/instances_val2017_subset.json \\\n")
        lines.append("  --output_json outputs/frcnn/rpn_recall.json\n```\n")

    # Figures
    lines.append("\n## 7) Qualitative figures (paths to include in PDF)\n")
    for label, p in [("Faster R-CNN", args.figures_frcnn), ("Mask R-CNN", args.figures_mask)]:
        pngs = sorted(p.glob("*.png")) if p.exists() else []
        lines.append(f"\n**{label}** (`{p}`): {len(pngs)} file(s)\n")
        for png in pngs[:20]:
            lines.append(f"- `{png.as_posix()}`\n")
        if len(pngs) > 20:
            lines.append(f"- _… and {len(pngs) - 20} more_\n")
        if not pngs:
            mt = "frcnn" if "frcnn" in p.as_posix() else "maskrcnn"
            ckpt = f"outputs/{mt}/best_model.pt"
            lines.append(
                f"_None — run:_ `python scripts/visualize_predictions.py --data_root data/coco_subset "
                f"--model_type {mt} --checkpoint {ckpt} --output_dir {p.as_posix()}`\n"
            )

    md_path = out_dir / "report_tables.md"
    write_md(md_path, "".join(lines))
    print(f"Wrote {md_path}")

    narrative_path = out_dir / "report_narrative_draft.md"
    write_md(
        narrative_path,
        build_narrative_draft(
            best_f, best_m, last_f, last_m, hist_f, hist_m, args.rpn_json.exists(), out_dir
        ),
    )
    print(f"Wrote {narrative_path}")

    # --- LaTeX ---
    tex: List[str] = []
    tex.append("% --- Faster R-CNN (best bbox epoch) ---\n")
    if best_f:
        tex.append("\\begin{tabular}{lr}\n\\hline\n")
        for lab, k in zip(labels, bkeys):
            tex.append(f"{lab} & {fmt(best_f.get(k))} \\\\\n")
        tex.append("\\hline\n\\end{tabular}\n\n")

    tex.append("% --- Mask R-CNN bbox + mask (best bbox epoch) ---\n")
    if best_m:
        tex.append("\\begin{tabular}{lr}\n\\hline\n")
        tex.append("\\multicolumn{2}{c}{Bounding box} \\\\\n\\hline\n")
        for lab, k in zip(labels, bkeys):
            tex.append(f"{lab} & {fmt(best_m.get(k))} \\\\\n")
        tex.append("\\hline\n\\multicolumn{2}{c}{Instance segmentation} \\\\\n\\hline\n")
        for lab, k in zip(
            ["Mask AP", "Mask AP50", "Mask AP75", "Mask APs", "Mask APm", "Mask APl"],
            segm_keys(),
        ):
            tex.append(f"{lab} & {fmt(best_m.get(k))} \\\\\n")
        tex.append("\\hline\n\\end{tabular}\n")

    tex_path = out_dir / "report_tables.tex"
    tex_path.write_text("".join(tex), encoding="utf-8")
    print(f"Wrote {tex_path}")

    # --- CSV flat ---
    csv_path = out_dir / "metrics_summary.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["model", "epoch_type", "epoch", "loss"] + bkeys + segm_keys())
        for name, best, last in [
            ("faster_rcnn", best_f, last_f),
            ("mask_rcnn", best_m, last_m),
        ]:
            if best:
                row = [name, "best_bbox_ap", best.get("epoch"), best.get("loss")]
                row += [best.get(k) for k in bkeys]
                row += [best.get(k) for k in segm_keys()]
                w.writerow(row)
            if last and last is not best:
                row = [name, "last", last.get("epoch"), last.get("loss")]
                row += [last.get(k) for k in bkeys]
                row += [last.get(k) for k in segm_keys()]
                w.writerow(row)
    print(f"Wrote {csv_path}")

    # RPN CSV
    if args.rpn_json.exists():
        with args.rpn_json.open(encoding="utf-8") as f:
            rpn = json.load(f)
        rpn_csv = out_dir / "rpn_recall_table.csv"
        with rpn_csv.open("w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["metric", "mean_recall"])
            for key in sorted(rpn.get("mean_recall", {}).keys()):
                w.writerow([key, rpn["mean_recall"][key]])
        print(f"Wrote {rpn_csv}")

    # --- Checklist ---
    chk: List[str] = []
    chk.append("CASE STUDY 2 — REPORT CHECKLIST (align with course PDF)\n")
    chk.append("=" * 60 + "\n\n")
    chk.append("[ ] Abstract (max 1 page per assignment)\n")
    chk.append("[ ] Introduction / motivation\n")
    chk.append("[ ] Methodology (Faster R-CNN: backbone, FPN, RPN, anchors, RoI head)\n")
    chk.append("[ ] Methodology (Mask R-CNN: RoI Align, mask branch, L = Lcls+Lbox+Lmask)\n")
    chk.append("[ ] Experimental setup: hardware, conda env, PyTorch/CUDA build, Slurm partition\n")
    chk.append("[ ] Data: COCO subset 3000/500, seed, how subset was built (build_coco_subset.py)\n")
    chk.append("[ ] Hyperparameters: epochs, batch size, LR, optimizer (from Slurm / train scripts)\n")
    chk.append("[ ] Table: bbox AP, AP50, AP75, APs/m/l — Faster vs Mask (use metrics_summary.csv)\n")
    chk.append("[ ] Table: mask AP metrics — Mask R-CNN only\n")
    chk.append("[ ] RPN analysis: recall vs IoU and vs # proposals (rpn_recall_table.csv + discussion)\n")
    chk.append("[ ] Figures: qualitative examples (outputs/figures/...)\n")
    chk.append("[ ] Tradeoffs: time, memory, accuracy, mask branch cost\n")
    chk.append("[ ] Conclusion + limitations\n")
    chk.append("[ ] Attach: training logs (.out), Slurm scripts, code link or zip\n\n")
    chk.append("Generated files:\n")
    chk.append(f"  - {md_path.resolve()}\n")
    chk.append(f"  - {(out_dir / 'report_narrative_draft.md').resolve()}\n")
    chk.append(f"  - {tex_path.resolve()}\n")
    chk.append(f"  - {csv_path.resolve()}\n")
    if args.rpn_json.exists():
        chk.append(f"  - {(out_dir / 'rpn_recall_table.csv').resolve()}\n")
    chk.append("\nSource metrics:\n")
    chk.append(f"  - {args.frcnn_metrics}\n")
    chk.append(f"  - {args.maskrcnn_metrics}\n")

    chk_path = out_dir / "REPORT_CHECKLIST.txt"
    chk_path.write_text("".join(chk), encoding="utf-8")
    print(f"Wrote {chk_path}")

    print("\nNext: edit report_narrative_draft.md, copy report_tables.md + figures into your PDF.")


if __name__ == "__main__":
    main()
